# 

FF_APP_FSPATH=/Applications/Firefox.App
FF_BIN_FSPATH=/Applications/Firefox.app/Contents/MacOS/firefox

PROFILE_X_FSPATH=

# TODO: DNS Set..
# TODO:https://github.com/pyllyukko/user.js/

run:
	$(FF_BIN_FSPATH) -h

1:
	$(FF_BIN_FSPATH) --ProfileManager

2: 
	$(FF_BIN_FSPATH) --profile



